import ThemeToggle from './theme-toggle';
import Link from 'next/link';
import {ArrowUpRight, ArrowRight, Code2, GitBranch, GitPullRequest, ShieldCheck, Check, Terminal} from 'lucide-react';

export default function Landing(){return <div className="landing">
 <a className="skip-link" href="#main-content">Skip to content</a>
 <header className="landing-nav"><Link href="/" className="landing-brand"><Code2 size={22}/>RepoPilot<span>BETA</span></Link><nav aria-label="Main navigation"><a href="#workflow">How it works</a><Link href="/guide/">User guide</Link><a href="#evidence">The evidence</a><a href="https://github.com/thanos07/repopilot" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a></nav><ThemeToggle/><Link href="/workspace/" className="landing-nav-cta">Explore preview <ArrowUpRight size={15}/></Link></header>
 <main id="main-content">
 <section className="hero"><div className="hero-copy"><div className="landing-eyebrow"><span/> YOUR REPOSITORY. YOUR FINAL CALL.</div><h1>A little less toil.<br/>A lot more <em>control.</em></h1><p>An AI coding workspace for small Python fixes in public GitHub repositories. Follow the plan, inspect the diff, and see the test evidence before a draft pull request goes out.</p><div className="hero-actions"><Link href="/workspace/" className="landing-primary">Explore the workspace <ArrowRight size={17}/></Link><a href="#workflow" className="landing-text-link">See how it works <span>↓</span></a></div><div className="hero-footnote"><ShieldCheck size={15}/> Read-only public preview · Operator workflow demonstrated below.</div></div><div className="hero-index"><span>01 / THE WORKSPACE</span><span>BUILT FOR THOUGHTFUL SHIPPING</span></div>
 <div className="showcase"><div className="showcase-top"><span><i/> A change, ready for a closer look</span><span>RECORDED DEMO</span></div><div className="showcase-body"><aside className="showcase-aside"><span className="landing-eyebrow">THE BRIEF</span><h2>Make every<br/>quantity count.</h2><p>Fix shopping cart totals for multiple quantities.</p><span className="showcase-repo"><GitBranch size={14}/> mdtnoor/repopilot-demo</span><div className="showcase-steps"><span><Check size={14}/> Inspect the repository</span><span><Check size={14}/> Prepare the patch</span><span><Check size={14}/> Verify the change</span><span><ShieldCheck size={14}/> Human review</span></div></aside><div className="showcase-code"><div className="code-caption"><span><Code2 size={16}/> cart.py</span><span>SIMPLIFIED DIFF</span></div><pre><code><span className="code-dim">def calculate_total(items):</span>{'\n'}<span className="code-minus">−    return sum(item["price_cents"] for item in items)</span>{'\n'}<span className="code-plus">+    return sum(</span>{'\n'}<span className="code-plus">+        item["price_cents"] * item["quantity"]</span>{'\n'}<span className="code-plus">+        for item in items</span>{'\n'}<span className="code-plus">+    )</span></code></pre><div className="showcase-result"><span><Check size={16}/> 6 tests passed</span><span>2 files changed</span><span>Draft PR #1</span></div><p className="showcase-disclaimer">An illustration of the recorded shopping-cart demo. Open the published PR for the exact patch.</p></div></div><a className="showcase-bottom" href="https://github.com/mdtnoor/repopilot-demo/pull/1" target="_blank" rel="noreferrer"><span><GitPullRequest size={17}/> Explore the published demo</span><ArrowUpRight size={18}/></a></div>
 </section>
 <section className="workflow-section" id="workflow"><div className="section-intro"><span className="landing-eyebrow">02 / THE PROCESS</span><h2>From a brief to a diff.<br/><em>With you in the loop.</em></h2><p>The work is visible at every stage. You decide what is ready to leave the workspace.</p></div><div className="workflow-grid">{[{n:'01',title:'Give it a clear brief.',text:'Choose a repository and describe the change. Keep the task focused and the expected behavior explicit.',icon:Code2},{n:'02',title:'Watch the work unfold.',text:'Inspect the implementation plan, code changes, recorded activity, and sandbox test results.',icon:Terminal},{n:'03',title:'Review. Then publish.',text:'Approve the exact patch before creating a draft pull request. Review and merge on GitHub when ready.',icon:ShieldCheck}].map(({n,title,text,icon:Icon})=><article key={n}><div className="workflow-number"><span>{n}</span><Icon size={21}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="evidence-section" id="evidence"><div><span className="landing-eyebrow">03 / LESS PROMISE. MORE PROOF.</span><h2>A small task.<br/><em>A real workflow.</em></h2><p>Our shopping-cart demo went from failing tests to an approved patch and a published draft pull request.</p><a className="landing-text-link" href="https://github.com/thanos07/repopilot/tree/main/evals/results" target="_blank" rel="noreferrer">Read the evaluation records <ArrowUpRight size={16}/></a></div><div className="evidence-stats"><div><strong>6<span> / 6</span></strong><p>Final tests passed in the demo<br/><small>Baseline: 2 passed, 2 failed</small></p></div><div><strong>$0.00215</strong><p>Estimated model usage for that task<br/><small>Sandbox charges excluded</small></p></div><p className="evidence-note">One successful demo is not a reliability benchmark. Evaluation records include an unsuccessful run and a separately recorded run after clarifying its task description.</p></div></section>
 <section className="landing-end"><span className="landing-eyebrow">KEEP THE FINAL CALL.</span><h2>Make the next change<br/><em>one you can inspect.</em></h2><Link href="/workspace/" className="landing-primary">Explore preview <ArrowRight size={17}/></Link><p>This public release is a read-only portfolio preview. Public signup and live task execution are planned for a future update.</p></section>
 </main><footer className="landing-footer"><Link href="/" className="landing-brand"><Code2 size={20}/>RepoPilot</Link><Link href="/guide/">User guide</Link><span>Built by <a href="https://portfolio-rosy-psi-74.vercel.app/" target="_blank" rel="noreferrer">Md Noor <ArrowUpRight size={13}/></a></span><a href="https://github.com/thanos07/repopilot" target="_blank" rel="noreferrer">View source <ArrowUpRight size={14}/></a></footer>
 </div>}

