# Generated by Django 5.2.16 on 2026-09-10 18:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('PREPARING', 'Preparing'), ('ANALYZING', 'Analyzing'), ('PLANNING', 'Planning'), ('IMPLEMENTING', 'Implementing'), ('TESTING', 'Testing'), ('REVIEWING', 'Reviewing'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('APPROVED', 'Approved'), ('PUBLISHING', 'Publishing'), ('PR_CREATED', 'Pr Created'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=24)),
                ('base_sha', models.CharField(blank=True, max_length=40)),
                ('plan', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('limitation', models.TextField(blank=True)),
                ('max_iterations', models.PositiveIntegerField(default=20)),
                ('max_tools', models.PositiveIntegerField(default=40)),
                ('max_test_runs', models.PositiveIntegerField(default=5)),
                ('max_seconds', models.PositiveIntegerField(default=900)),
                ('max_cost', models.DecimalField(decimal_places=6, default='0.50', max_digits=10)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repositories.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='RUNNING', max_length=20)),
                ('sandbox_id', models.CharField(blank=True, max_length=180)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('tool_count', models.PositiveIntegerField(default=0)),
                ('stop_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='coding_tasks.codingtask')),
            ],
        ),
        migrations.CreateModel(
            name='PatchSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_sha', models.CharField(max_length=40)),
                ('digest', models.CharField(max_length=64)),
                ('diff', models.TextField()),
                ('files', models.JSONField(default=list)),
                ('contents', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='coding_tasks.codingtask')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequestPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('pr_url', models.URLField(blank=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coding_tasks.patchset')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='coding_tasks.codingtask')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(default='APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coding_tasks.patchset')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='coding_tasks.codingtask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='coding_tasks.codingtask')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_digest', models.CharField(blank=True, max_length=64)),
                ('phase', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('exit_code', models.IntegerField(null=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_tasks.agentrun')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='coding_tasks.codingtask')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_model', models.CharField(max_length=120)),
                ('returned_model', models.CharField(max_length=120)),
                ('input_tokens', models.PositiveIntegerField()),
                ('cached_tokens', models.PositiveIntegerField(null=True)),
                ('output_tokens', models.PositiveIntegerField()),
                ('rates', models.JSONField(default=dict)),
                ('estimated_cost', models.DecimalField(decimal_places=8, max_digits=14)),
                ('latency_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='coding_tasks.agentrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='coding_tasks.agentrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='unique_run_step')],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=60)),
                ('arguments', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(default='STARTED', max_length=20)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='coding_tasks.agentrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='unique_run_tool')],
            },
        ),
    ]
