# Generated by Django 5.2.16 on 2026-09-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingtask',
            name='max_cost',
            field=models.DecimalField(decimal_places=6, default='0.05', max_digits=10),
        ),
        migrations.AlterField(
            model_name='codingtask',
            name='max_iterations',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='codingtask',
            name='max_test_runs',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='codingtask',
            name='max_tools',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
